package org.poc.objs.sbom.demo

import java.util.UUID

data class DemoDatasetSpec(
    val name: String,
    val datasetType: String,
    val classification: String,
    val description: String,
    val categoryId: UUID,
)

object SbomDemoDatasets {
    val all: List<DemoDatasetSpec> =
        listOf(
            ds("customer-golden-record", "analytical", "restricted", "Conformed party and address golden record", SbomDemoIds.CATEGORY_DATA),
            ds("customer-pii-vault", "operational", "restricted", "Encrypted identifiers, national IDs, and contact PII", SbomDemoIds.CATEGORY_DATA),
            ds("kyc-document-index", "operational", "confidential", "KYC pack metadata and document checksums", SbomDemoIds.CATEGORY_DIGITAL),
            ds("kyc-screening-hits", "operational", "confidential", "Sanctions and PEP screening outcomes", SbomDemoIds.CATEGORY_DATA),
            ds("onboarding-application-facts", "operational", "confidential", "Digital account-opening application facts", SbomDemoIds.CATEGORY_DIGITAL),
            ds("retail-account-master", "operational", "confidential", "Retail current and savings account master", SbomDemoIds.CATEGORY_RETAIL),
            ds("retail-balance-snapshots", "analytical", "confidential", "End-of-day retail balance snapshots", SbomDemoIds.CATEGORY_RETAIL),
            ds("card-account-master", "operational", "restricted", "Card PAN tokens, expiry, and product codes", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("card-authorization-stream", "operational", "confidential", "Authorization request/response stream", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("card-clearing-files", "operational", "confidential", "Scheme clearing and presentment files", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("payment-initiation-log", "operational", "confidential", "ISO 20022 pain.001 initiation log", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("payment-confirmation-log", "operational", "confidential", "pain.002 and pacs.002 confirmations", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("ach-nacha-batches", "operational", "confidential", "NACHA originating and receiving batches", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("merchant-terminal-master", "operational", "internal", "Acquiring MID/TID and MCC catalog", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("merchant-settlement-ledger", "operational", "confidential", "Merchant capture and settlement ledger", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("fraud-feature-store-online", "analytical", "confidential", "Online fraud features for card and A2A", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("fraud-score-history", "analytical", "confidential", "Model scores and rule-hit explanations", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("settlement-nostro-positions", "operational", "confidential", "Nostro/vostro positions by currency", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("billing-invoice-lines", "operational", "confidential", "Commercial invoice headers and lines", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("atm-switch-journal", "operational", "confidential", "ISO 8583 ATM/POS switch journal", SbomDemoIds.CATEGORY_PAYMENTS),
            ds("open-banking-consents", "operational", "restricted", "PSD2 AIS/PIS consents and TPP identities", SbomDemoIds.CATEGORY_DIGITAL),
            ds("open-banking-transactions", "operational", "confidential", "AIS transaction payloads for consented accounts", SbomDemoIds.CATEGORY_DIGITAL),
            ds("mobile-session-telemetry", "analytical", "internal", "Mobile BFF session and crash telemetry", SbomDemoIds.CATEGORY_DIGITAL),
            ds("online-banking-clickstream", "analytical", "internal", "Web clickstream with hashed party keys", SbomDemoIds.CATEGORY_DIGITAL),
            ds("notification-delivery-log", "operational", "internal", "Email/SMS/push delivery and bounce log", SbomDemoIds.CATEGORY_DIGITAL),
            ds("auth-event-audit", "operational", "restricted", "OIDC login, step-up, and token audit", SbomDemoIds.CATEGORY_DIGITAL),
            ds("contact-center-call-audio-index", "operational", "restricted", "Call recording index and retention holds", SbomDemoIds.CATEGORY_DIGITAL),
            ds("contact-center-transcripts", "analytical", "confidential", "ASR transcripts and agent annotations", SbomDemoIds.CATEGORY_DIGITAL),
            ds("loyalty-points-ledger", "operational", "internal", "Loyalty earn/burn ledger", SbomDemoIds.CATEGORY_DIGITAL),
            ds("branch-appointment-book", "operational", "internal", "Branch teller appointment book", SbomDemoIds.CATEGORY_RETAIL),
            ds("loan-application-facts", "operational", "confidential", "Unsecured and mortgage origination facts", SbomDemoIds.CATEGORY_RETAIL),
            ds("loan-collateral-register", "operational", "confidential", "Mortgage collateral and valuation register", SbomDemoIds.CATEGORY_RETAIL),
            ds("collections-strategy-outcomes", "analytical", "confidential", "Delinquency strategy A/B outcomes", SbomDemoIds.CATEGORY_RETAIL),
            ds("holdings-positions-eod", "operational", "confidential", "Wealth holdings EOD positions", SbomDemoIds.CATEGORY_WEALTH),
            ds("model-portfolio-weights", "operational", "internal", "Advisor model portfolio weights", SbomDemoIds.CATEGORY_WEALTH),
            ds("performance-attribution", "analytical", "confidential", "Brinson-Fachler performance attribution", SbomDemoIds.CATEGORY_WEALTH),
            ds("order-blotter", "operational", "confidential", "Advisor order blotter and fills", SbomDemoIds.CATEGORY_WEALTH),
            ds("market-ticks-equity", "analytical", "internal", "Normalized equity tick history", SbomDemoIds.CATEGORY_WEALTH),
            ds("market-ticks-fx", "analytical", "internal", "Normalized FX tick history", SbomDemoIds.CATEGORY_WEALTH),
            ds("market-ticks-fixed-income", "analytical", "internal", "Bond quotes and reference data", SbomDemoIds.CATEGORY_WEALTH),
            ds("research-notes", "operational", "confidential", "Published investment research notes", SbomDemoIds.CATEGORY_WEALTH),
            ds("nav-share-class", "operational", "confidential", "Fund NAV and share-class accounting", SbomDemoIds.CATEGORY_WEALTH),
            ds("suitability-assessments", "operational", "restricted", "MiFID suitability questionnaires", SbomDemoIds.CATEGORY_WEALTH),
            ds("policy-life-master", "operational", "confidential", "Life policy master and riders", SbomDemoIds.CATEGORY_INSURANCE),
            ds("policy-pc-master", "operational", "confidential", "P&C policy master and coverages", SbomDemoIds.CATEGORY_INSURANCE),
            ds("fnol-intake", "operational", "confidential", "First notice of loss intake", SbomDemoIds.CATEGORY_INSURANCE),
            ds("claims-payments", "operational", "confidential", "Claims reserve and payment ledger", SbomDemoIds.CATEGORY_INSURANCE),
            ds("underwriting-referrals", "operational", "confidential", "Underwriting referral queue", SbomDemoIds.CATEGORY_INSURANCE),
            ds("rating-tables", "operational", "internal", "Broker quote rating tables", SbomDemoIds.CATEGORY_INSURANCE),
            ds("broker-book-of-business", "operational", "confidential", "External broker book of business", SbomDemoIds.CATEGORY_INSURANCE),
            ds("reinsurance-bordereaux", "operational", "confidential", "Cession bordereaux and recoveries", SbomDemoIds.CATEGORY_INSURANCE),
            ds("cash-sweep-instructions", "operational", "confidential", "Corporate cash sweep instructions", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("lc-guarantee-register", "operational", "confidential", "Letters of credit and guarantees", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("fx-spot-forward-curves", "analytical", "internal", "FX spot/forward curves and spreads", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("swift-mx-archive", "operational", "restricted", "SWIFTNet MX message archive", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("collateral-inventory", "operational", "confidential", "Eligible collateral inventory", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("margin-call-log", "operational", "confidential", "VM/IM margin call log", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("custody-tax-lots", "operational", "confidential", "Custody tax lots and corporate actions", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("trade-finance-documents", "operational", "confidential", "Bill of lading and invoice images index", SbomDemoIds.CATEGORY_CORPORATE_BANKING),
            ds("aml-wire-monitor", "analytical", "restricted", "AML wire and high-risk corridor monitor", SbomDemoIds.CATEGORY_DATA),
            ds("aml-sar-cases", "operational", "restricted", "SAR case files and filing status", SbomDemoIds.CATEGORY_DATA),
            ds("credit-pd-features", "analytical", "confidential", "Probability-of-default feature table", SbomDemoIds.CATEGORY_DATA),
            ds("credit-lgd-features", "analytical", "confidential", "Loss-given-default feature table", SbomDemoIds.CATEGORY_DATA),
            ds("credit-scorecards-batch", "analytical", "confidential", "Monthly PD/LGD score batches", SbomDemoIds.CATEGORY_DATA),
            ds("feature-store-offline", "analytical", "confidential", "Offline point-in-time feature store", SbomDemoIds.CATEGORY_DATA),
            ds("feature-store-online-kv", "operational", "confidential", "Online feature key-value store", SbomDemoIds.CATEGORY_DATA),
            ds("ml-experiment-metrics", "analytical", "internal", "Training runs, metrics, and artifacts index", SbomDemoIds.CATEGORY_DATA),
            ds("nbp-ranking-features", "analytical", "confidential", "Next-best-product ranking features", SbomDemoIds.CATEGORY_DATA),
            ds("document-ocr-extractions", "analytical", "restricted", "OCR fields from KYC document packs", SbomDemoIds.CATEGORY_DATA),
            ds("iceberg-customer-360", "analytical", "restricted", "Iceberg customer-360 fact tables", SbomDemoIds.CATEGORY_DATA),
            ds("data-catalog-glossary", "operational", "internal", "Business glossary and dataset ownership", SbomDemoIds.CATEGORY_DATA),
            ds("dataset-lineage-edges", "analytical", "internal", "Dataset-to-job lineage edges", SbomDemoIds.CATEGORY_DATA),
            ds("feature-job-definitions", "operational", "internal", "Feature pipeline job definitions", SbomDemoIds.CATEGORY_DATA),
            ds("esg-financed-emissions", "analytical", "internal", "PCAF financed-emissions inventory", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("esg-counterparty-scores", "analytical", "internal", "Counterparty ESG scores and sources", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("hr-employee-master", "operational", "restricted", "People Center employee master", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("hr-leave-balances", "operational", "confidential", "Leave balances and requests", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("hr-org-chart", "operational", "internal", "Reporting lines and cost centers", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("payroll-gross-to-net", "operational", "restricted", "Gross-to-net payroll calculations", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("procurement-vendors", "operational", "internal", "Vendor master and tax IDs", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("purchase-orders", "operational", "internal", "Purchase orders and receipts", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("gl-subledger-close", "operational", "confidential", "Subledger to GL close extracts", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("legal-matters", "operational", "restricted", "Legal matters, holds, and counsel", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("expense-reports", "operational", "confidential", "T&E expense reports and receipts index", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("vendor-risk-questionnaires", "operational", "confidential", "Third-party risk questionnaires", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("workplace-badge-events", "operational", "confidential", "Badge-in events for offices", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("hvac-occupancy-telemetry", "analytical", "internal", "HVAC and occupancy telemetry", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("desk-booking-calendar", "operational", "internal", "Desk and room booking calendar", SbomDemoIds.CATEGORY_CORP_FUNCTIONS),
            ds("api-gateway-access-log", "analytical", "internal", "Edge API access and WAF log", SbomDemoIds.CATEGORY_PLATFORM),
            ds("idp-audit-trail", "operational", "restricted", "Workforce SSO and PAM audit trail", SbomDemoIds.CATEGORY_PLATFORM),
            ds("cicd-pipeline-runs", "operational", "internal", "Tekton/Jenkins pipeline run history", SbomDemoIds.CATEGORY_PLATFORM),
            ds("observability-metrics-1m", "analytical", "internal", "One-minute metrics rollups", SbomDemoIds.CATEGORY_PLATFORM),
            ds("observability-traces", "analytical", "internal", "Distributed traces sampled 1%", SbomDemoIds.CATEGORY_PLATFORM),
            ds("k8s-cluster-inventory", "operational", "internal", "Cluster, node, and namespace inventory", SbomDemoIds.CATEGORY_PLATFORM),
            ds("secrets-rotation-log", "operational", "restricted", "App-role secret rotation log", SbomDemoIds.CATEGORY_PLATFORM),
            ds("inner-source-catalog", "operational", "internal", "Inner-source service catalog", SbomDemoIds.CATEGORY_PLATFORM),
            ds("service-mesh-policies", "operational", "internal", "mTLS and traffic-split policies", SbomDemoIds.CATEGORY_PLATFORM),
            ds("chaos-experiment-results", "analytical", "internal", "Game-day experiment results", SbomDemoIds.CATEGORY_PLATFORM),
            ds("pci-evidence-store", "operational", "restricted", "PCI-DSS control evidence artifacts", SbomDemoIds.CATEGORY_PLATFORM),
            ds("data-residency-inventory", "analytical", "confidential", "EU residency tags on datasets and stores", SbomDemoIds.CATEGORY_DATA),
        )

    init {
        require(all.size == 100) { "Expected 100 demo datasets, found ${all.size}" }
        require(all.map { it.name }.distinct().size == 100) { "Dataset names must be unique" }
    }

    private fun ds(
        name: String,
        datasetType: String,
        classification: String,
        description: String,
        categoryId: UUID,
    ) = DemoDatasetSpec(name, datasetType, classification, description, categoryId)
}
